export const GRIDFS_CONNECTION_TOKEN = 'GRIDFS_CONNECTION_TOKEN';
export const GRIDFS_BUCKET_NAME_TOKEN = 'GRIDFS_BUCKET_NAME_TOKEN';
export const GRIDFS_MODEL_NAME = 'GridFsFile';
export const GRIDFS_CHUNK_SIZE_TOKEN = 'GRIDFS_CHUNK_SIZE_TOKEN';
export const GRIDFS_FILES_MODEL_TOKEN = 'GRIDFS_FILES_MODEL_TOKEN';
export const GRIDFS_CHUNKS_MODEL_TOKEN = 'GRIDFS_CHUNKS_MODEL_TOKEN';
export const DEFAULT_CHUNK_SIZE = 261120; // 255 KB
